<#
  run_context_callers_dedup_and_version.ps1 --
  A `context` bundle lists each call SITE once, and its header names the engine
  that wrote it.

  DEFECT 1 (measured 2026-09-27, engine 1.18.0-alpha, re-measured 1.19.1).
    context --task "modify DRagLint.Lint.ConfigWriter.TLintConfigWriter.SaveToFile"
      --db src\delphi-plugin\_D-RAG\dclDragLintWizard.sqlite
  printed `## Callers (2)` with the SAME entry twice, LintOptionsFrame.pas:1454:23,
  while `query find-callers` said one. The site is a class-method call
  `TLintConfigWriter.SaveToFile(CP, Cfg)`, and the index holds TWO refs there: a
  `call` bound to the method and an unbound `member-access` on the same span.
  FindCallersByNameWithContext is kind-blind by design (other consumers want
  both), so the bundler has to dedupe on the position before it caps and counts.
  A doubled count is the mirror of the "zero callers is a defect" trap, and it
  spends the caller cap on repeats.

  DEFECT 2. The header said `Generated by drag-lint v0.18` -- the release that
  ADDED the bundle -- for every engine since.

  THE CONTROLS, and what each rules out:
    * two DISTINCT sites of the same method give `Callers (2)`
      -> the dedupe is on the position, not on the file or the name
    * --max-callers 1 on the two-site fixture gives exactly one entry
      -> the cap still applies after the dedupe
    * the header version equals what `--version` prints, not merely "not v0.18"

  Run from any CWD, pwsh 7. Builds its own fixture; touches no shared index.
#>
[CmdletBinding()]
param(
  [string]$Exe     = "$PSScriptRoot\..\..\third_party\dll-win64\drag-lint.exe",
  [string]$WorkDir = "C:\TEMP\draglint_context_callers_dedup_$PID"
)
try {
$ErrorActionPreference = 'Stop'
$script:fail = $false
function Check($n,$ok,$d){
  Write-Host ("[{0}] {1}" -f (@('FAIL','PASS')[[int]$ok]),$n) -ForegroundColor (@('Red','Green')[[int]$ok])
  if(-not $ok){ if($d){ Write-Host "      $d" -ForegroundColor DarkGray }; $script:fail=$true }
}
function Write-Ascii($p,$t){ [IO.File]::WriteAllText($p, (($t -replace "`r`n","`n") -replace "`n","`r`n"), [Text.Encoding]::ASCII) }

$exePath = (Resolve-Path $Exe).Path
if (Test-Path $WorkDir) { [IO.Directory]::Delete($WorkDir, $true) }

# ---- fixture A: exactly ONE call site, a class-method call ------------------
$srcA = Join-Path $WorkDir 'one'
New-Item -ItemType Directory -Path $srcA -Force | Out-Null
Write-Ascii (Join-Path $srcA 'uW.pas') @"
unit uW;

interface

type
  TW = class
  public
    class procedure Save(const AName: string);
  end;

implementation

class procedure TW.Save(const AName: string);
begin
end;

end.
"@
Write-Ascii (Join-Path $srcA 'uUse.pas') @"
unit uUse;

interface

procedure Run;

implementation

uses uW;

procedure Run;
begin
  TW.Save('a');
end;

end.
"@

# ---- fixture B: the same method called from TWO distinct sites --------------
$srcB = Join-Path $WorkDir 'two'
New-Item -ItemType Directory -Path $srcB -Force | Out-Null
Copy-Item (Join-Path $srcA 'uW.pas') $srcB
Write-Ascii (Join-Path $srcB 'uUse.pas') @"
unit uUse;

interface

procedure Run;

implementation

uses uW;

procedure Run;
begin
  TW.Save('a');
  TW.Save('b');
end;

end.
"@

$dbA = Join-Path $WorkDir 'one.sqlite'
$dbB = Join-Path $WorkDir 'two.sqlite'
& $exePath index $srcA --db $dbA 2>&1 | Out-Null
& $exePath index $srcB --db $dbB 2>&1 | Out-Null
Check 'V fixture index A was built' (Test-Path $dbA) $dbA
Check 'V fixture index B was built' (Test-Path $dbB) $dbB

function Bundle([string]$Db, [string[]]$Extra = @()) {
  return ((& $exePath context --task 'modify uW.TW.Save' --db $Db --format markdown @Extra 2>$null) -join "`n")
}
function CallerCount([string]$Text) {
  if ($Text -match '## Callers \((\d+)\)') { return [int]$Matches[1] }
  return -1
}
function CallerLines([string]$Text) {
  return @(($Text -split "`n") | Where-Object { $_ -match '^- .*uUse\.pas:\d+:\d+' })
}

# The fixture must reproduce the SHAPE: two refs at one position. Without it the
# single-site assertion below passes on the broken engine and proves nothing.
$shape = & $exePath sql --db $dbA --json --query "SELECT COUNT(*) AS n FROM refs r JOIN files f ON f.id = r.file_id WHERE r.name_text = 'Save' AND f.path LIKE '%uUse.pas'" 2>$null | ConvertFrom-Json
$nRefs = [int]$shape.rows[0][0]
Check "V the fixture holds more than one ref at the single call site (got $nRefs)" ($nRefs -ge 2) `
      'the extractor no longer emits call + member-access at one span; T1 would be vacuous -- rebuild the fixture'

# ---- T1: one site -> one caller ----------------------------------------------
$a = Bundle $dbA
Check 'T1 a single call site is listed ONCE: Callers (1)' ((CallerCount $a) -eq 1) ("Callers count = $(CallerCount $a)")
Check 'T1b and exactly one caller line is printed' ((CallerLines $a).Count -eq 1) ((CallerLines $a) -join ' | ')

# ---- P1: two sites -> two callers (the dedupe is on position) ---------------
$b = Bundle $dbB
Check 'P1 POSITIVE CONTROL two distinct sites give Callers (2)' ((CallerCount $b) -eq 2) ("Callers count = $(CallerCount $b)")
$bl = @(CallerLines $b | ForEach-Object { ($_ -replace '^- ', '').Trim() })
Check 'P1b and the two lines name two different positions' (($bl | Select-Object -Unique).Count -eq 2) ($bl -join ' | ')

# ---- P2: the cap still applies after the dedupe -----------------------------
$c = Bundle $dbB @('--max-callers', '1')
Check 'P2 --max-callers 1 prints exactly one caller line' ((CallerLines $c).Count -eq 1) ((CallerLines $c) -join ' | ')

# ---- T2: the header names the running engine --------------------------------
$ver = ((& $exePath --version 2>$null) -join ' ')
$verNum = if ($ver -match '(\d+\.\d+\.\d+[-\w]*)') { $Matches[1] } else { '' }
Check 'V --version printed a version number' ($verNum -ne '') $ver
Check "T2 the bundle header names the running engine (v$verNum)" `
      ($a -match ('Generated by drag-lint v' + [regex]::Escape($verNum) + ' at ')) `
      (($a -split "`n" | Where-Object { $_ -match 'Generated by' }) -join ' ')
Check 'T2b the header no longer claims v0.18' (-not ($a -match 'drag-lint v0\.18 ')) ''

Write-Host ''
if ($script:fail) { Write-Host 'FAIL' -ForegroundColor Red; exit 1 }
Write-Host 'PASS' -ForegroundColor Green; exit 0
} finally {
  # D23: this run's scratch is $PID-suffixed; remove it so per-run folders do not pile up in TEMP.
  foreach ($d23 in @("C:\TEMP\draglint_context_callers_dedup_$PID")) { if (Test-Path -LiteralPath $d23) { Remove-Item -LiteralPath $d23 -Recurse -Force -ErrorAction SilentlyContinue } }
}
