program drag_lint;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  TreeSitter in '..\..\third_party\delphi-tree-sitter\TreeSitter.pas',
  TreeSitterLib in '..\..\third_party\delphi-tree-sitter\TreeSitterLib.pas',
  TreeSitter.Query in '..\..\third_party\delphi-tree-sitter\TreeSitter.Query.pas',
  DRagLint.Core.Model in '..\core\DRagLint.Core.Model.pas',
  DRagLint.Core.Interfaces in '..\core\DRagLint.Core.Interfaces.pas',
  DRagLint.Wiring in '..\core\DRagLint.Wiring.pas',
  DRagLint.Core.Indexer in '..\core\DRagLint.Core.Indexer.pas',
  DRagLint.Storage.Schema in '..\storage\DRagLint.Storage.Schema.pas',
  DRagLint.Storage.SQLite in '..\storage\DRagLint.Storage.SQLite.pas',
  DRagLint.Parser.Delphi13 in '..\parser\DRagLint.Parser.Delphi13.pas',
  DRagLint.Parser.SpringDI in '..\parser\DRagLint.Parser.SpringDI.pas',
  DRagLint.Parser.DFM in '..\parser\DRagLint.Parser.DFM.pas',
  DRagLint.Parser.Sql in '..\parser\DRagLint.Parser.Sql.pas',
  DRagLint.Sql.FbSnapshot in '..\sql\DRagLint.Sql.FbSnapshot.pas',
  DRagLint.Sql.OrmLinker in '..\sql\DRagLint.Sql.OrmLinker.pas',
  DRagLint.Parser.DocComments in '..\parser\DRagLint.Parser.DocComments.pas',
  DRagLint.Query.Fuzzy in '..\query\DRagLint.Query.Fuzzy.pas',
  DRagLint.Lint.Config in '..\lint\DRagLint.Lint.Config.pas',
  DRagLint.Lint.Baseline in '..\lint\DRagLint.Lint.Baseline.pas',
  DRagLint.Lint.QueryRules in '..\lint\DRagLint.Lint.QueryRules.pas',
  DRagLint.Lint.Linter in '..\lint\DRagLint.Lint.Linter.pas',
  DRagLint.Lint.ProjectChecks in '..\lint\DRagLint.Lint.ProjectChecks.pas',
  DRagLint.Lint.ProjectChecks.Parse in '..\lint\DRagLint.Lint.ProjectChecks.Parse.pas',
  DRagLint.Lint.ProjectRules in '..\lint\DRagLint.Lint.ProjectRules.pas',
  DRagLint.Project.Resolver in '..\project\DRagLint.Project.Resolver.pas',
  DRagLint.FormsMap in '..\forms\DRagLint.FormsMap.pas',
  DRagLint.MCP.Server in '..\mcp\DRagLint.MCP.Server.pas',
  DRagLint.LSP.Server in '..\lsp\DRagLint.LSP.Server.pas',
  DRagLint.LSP.Completion in '..\lsp\DRagLint.LSP.Completion.pas',
  DRagLint.Hover.Renderer in 'DRagLint.Hover.Renderer.pas',
  DRagLint.Context.Bundler in '..\context\DRagLint.Context.Bundler.pas',
  DRagLint.Resolver.TypeAt in '..\resolver\DRagLint.Resolver.TypeAt.pas',
  DRagLint.Refactor.Rename in '..\refactor\DRagLint.Refactor.Rename.pas',
  DRagLint.Refactor.DocStub in '..\refactor\DRagLint.Refactor.DocStub.pas',
  DRagLint.Refactor.DeadCode in '..\refactor\DRagLint.Refactor.DeadCode.pas',
  DRagLint.Refactor.TestStub in '..\refactor\DRagLint.Refactor.TestStub.pas',
  DRagLint.Format.Yadf in '..\refactor\DRagLint.Format.Yadf.pas',
  DRagLint.Diagnostics.CompileCheck in '..\diagnostics\DRagLint.Diagnostics.CompileCheck.pas',
  DRagLint.Diagnostics.AstChecks in '..\diagnostics\DRagLint.Diagnostics.AstChecks.pas',
  DRagLint.Diagnostics.NamingChecks in '..\diagnostics\DRagLint.Diagnostics.NamingChecks.pas',
  DRagLint.Diagnostics.ParseCache in '..\diagnostics\DRagLint.Diagnostics.ParseCache.pas',
  DRagLint.Analysis.Cfg in '..\analysis\DRagLint.Analysis.Cfg.pas',
  DRagLint.Analysis.DataFlow in '..\analysis\DRagLint.Analysis.DataFlow.pas',
  DRagLint.Analysis.Flow.Lattices in '..\analysis\DRagLint.Analysis.Flow.Lattices.pas',
  DRagLint.Diagnostics.FlowChecks in '..\diagnostics\DRagLint.Diagnostics.FlowChecks.pas',
  DRagLint.Output.Sarif in '..\output\DRagLint.Output.Sarif.pas',
  DRagLint.Output.ExitCode in '..\output\DRagLint.Output.ExitCode.pas',
  DRagLint.Workspace.Config in '..\workspace\DRagLint.Workspace.Config.pas',
  DRagLint.Index.Manifest in '..\index\DRagLint.Index.Manifest.pas',
  DRagLint.Index.Glob in '..\index\DRagLint.Index.Glob.pas',
  DRagLint.Index.IgnoreFiles in '..\index\DRagLint.Index.IgnoreFiles.pas',
  DRagLint.Index.Closure in '..\index\DRagLint.Index.Closure.pas',
  DRagLint.Index.Reconcile in '..\index\DRagLint.Index.Reconcile.pas',
  DRagLint.Index.Plan in '..\index\DRagLint.Index.Plan.pas',
  DRagLint.Index.DbSelect in '..\index\DRagLint.Index.DbSelect.pas',
  DRagLint.Index.Drift in '..\index\DRagLint.Index.Drift.pas',
  DRagLint.Index.Coverage in '..\index\DRagLint.Index.Coverage.pas',
  DRagLint.CLI in 'DRagLint.CLI.pas';

begin
  ExitCode := DRagLint.CLI.Run;
end.
